---
- name: install versions
  shell: ". {{ nvm_root }}/nvm.sh && nvm install {{ item }}"
  args: 
    executable: /bin/bash
  register: output
  changed_when: "'already installed.' not in output.stderr"
  with_items: "{{ nvm_node_versions }}"

- name: create alias directory
  file: path="{{ nvm_root }}/alias" state=directory

- name: set {{ nvm_default_node_version }} as default version
  copy: dest="{{ nvm_root }}/alias/default" content="{{ nvm_default_node_version }}"
