---
- name: install packages
  shell: ". {{ nvm_root }}/nvm.sh && nvm use {{ item.0 }} && npm install -g {{ item.1 }}"
  args:
    executable: /bin/bash
  with_nested:
    - "{{ nvm_node_versions }}"
    - "{{ nvm_global_packages }}"