---
- name: install packages for each user
  shell: ". {{ nvm_root }}/nvm.sh && nvm use {{ item.1 }} && npm install -g {{ item.2 }}"
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ item.0 }}"
  with_nested:
    - "{{ nvm_users }}"
    - "{{ nvm_node_versions }}"
    - "{{ nvm_global_packages }}"
